name: kokeilu
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build_and_test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo OoKoo
      - name: test php
        run: php -r "var_dump(date('c')); echo PHP_EOL;"
