name: kokeilu
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: "simulate build"
        run: php /home/vsj/github/actions-runner/dummyrunner 5
      - name: test
        run: php test.php
