name: tiedostokokeilu
on:
  workflow_dispatch:
  pull_request:
    branches: [master]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  relevance-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - id: check
        name: Determine stuff
        run: |
          git fetch --depth=1 origin ${{ github.base_ref }}
          if [[ $(git diff --name-only origin/${{ github.base_ref }} | grep -vPc '^.github/') > 0 ]] ;
          then status="skip"; echo "Hello world";
          else status="skip";
          fi
          echo "status=skip" >> $GITHUB_OUTPUT

  build_and_test:
    runs-on: ubuntu-latest
    needs: relevance-check
    if: needs.relevance-check.outputs.status == 'run'
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo ok
